version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    mem_limit: 1872m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
      - PGUSER=alfresco
    command: "
      postgres
        -c max_connections=200
        -c logging_collector=on
        -c log_min_messages=LOG"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    networks:
      - webproxy
    restart: unless-stopped


  alfresco:
    build:
      context: ./alfresco
      args:
        ALFRESCO_TAG: ${ALFRESCO_CE_TAG}
        DB: postgres
        SOLR_COMMS: secret
    mem_limit: 7488m
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TZ: "Africa/Bangui"
      JAVA_TOOL_OPTIONS: "
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      "
      JAVA_OPTS: "
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.driver=org.postgresql.Driver
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsystem.preferred.password.encoding=bcrypt10
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.port.ssl=8983
        -Dsolr.secureComms=secret
        -Dsolr.baseUrl=/solr
        -Dindex.subsystem.name=solr6
        -Dsolr.sharedSecret=${SOLR_SECRET:?Definir SOLR_SECRET dans .env}
        -Dalfresco.host=${SERVER_NAME}
        -Dalfresco.port=${SHARE_PORT}
        -Dapi-explorer.url=${PROTOCOL}://${SERVER_NAME}:${SHARE_PORT}/api-explorer
        -Dalfresco.protocol=${PROTOCOL}
        -Dshare.host=${SERVER_NAME}
        -Dshare.port=${SHARE_PORT}
        -Dshare.protocol=${PROTOCOL}
        -Daos.baseUrlOverwrite=${PROTOCOL}://${SERVER_NAME}/alfresco/aos
        -Dmessaging.subsystem.autoStart=false
        -Drepo.event2.enabled=false
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false
        -Dopencmis.server.override=true
        -Dopencmis.server.value=${PROTOCOL}://${SERVER_NAME}:${SHARE_PORT}
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dhttpclient.config.transform.connectionRequestTimeout=500000
        -Dalfresco.restApi.basicAuthScheme=true
        -Dauthentication.protection.enabled=false
        -XX:+UseG1GC -XX:+UseStringDeduplication
        -Dgoogledocs.enabled=false
        -Dmail.host=smtp.gmail.com
        -Dmail.port=587
        -Dmail.protocol=smtp
        -Dmail.smtp.auth=true
        -Dmail.smtp.starttls.enable=true
        -Dmail.username=gedmsp@gmail.com
        -Dmail.password=${MAIL_PASSWORD:?Definir MAIL_PASSWORD dans .env}
        -Dmail.encoding=UTF-8
        -Dmail.from.default=gedmsp@gmail.com
        -Dmail.from.enabled=false
        -Dmail.smtp.timeout=5000
        -Dmail.smtp.connectiontimeout=5000
        -Dmail.smtp.writetimeout=5000
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
      "
    volumes:
      - ./alfresco/extension/models:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/models
      - ./alfresco/extension/workflows:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/workflows
      - ./alfresco/extension/templates:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/templates
      - ./alfresco/extension/bootstrap:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/bootstrap
      - ./alfresco/extension/messages:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/messages
      - ./alfresco/extension/email-templates:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/email-templates
      - ./data/alf-repo-data:/usr/local/tomcat/alf_data
      - ./logs/alfresco:/usr/local/tomcat/logs
      - ./alfresco.svg:/usr/local/tomcat/webapps/api-explorer/images/logo.svg
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alfresco.rule=PathPrefix(`/alfresco`)"
      - "traefik.http.routers.alfresco.entrypoints=web,websecure"
      - "traefik.http.routers.alfresco.tls.certresolver=letsencrypt"
      - "traefik.http.services.alfresco.loadbalancer.server.port=8080"
    networks:
      - webproxy
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 1m
    restart: unless-stopped


  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:${TRANSFORM_ENGINE_TAG}
    mem_limit: 2048m
    environment:
      JAVA_OPTS: "
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
        -Dserver.tomcat.threads.max=12
        -Dserver.tomcat.threads.min=4
        -Dlogging.level.org.alfresco.transform.common.TransformerDebug=ERROR
        -Dlogging.level.org.alfresco.transform=ERROR
      "
    networks:
      - webproxy
    restart: unless-stopped


  share:
    build:
      context: ./share
      args:
        SHARE_TAG: ${SHARE_TAG}
        SERVER_NAME: ${SERVER_NAME}
        HTTP_PORT: 80
        PROTOCOL: ${PROTOCOL}
        SHARE_PORT: ${SHARE_PORT}
    mem_limit: 1872m
    environment:
      TZ: "Africa/Bangui"
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      CSRF_FILTER_REFERER: "${PROTOCOL}://${SERVER_NAME}/.*"
      CSRF_FILTER_ORIGIN: "${PROTOCOL}://${SERVER_NAME}"
      JAVA_OPTS: "
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
      "
    depends_on:
      alfresco:
        condition: service_healthy
    volumes:
      - ./logs/share:/usr/local/tomcat/logs
      - ./alfresco.svg:/usr/local/tomcat/webapps/share/components/images/alfresco-logo.svg
      - ./alfresco.svg:/usr/local/tomcat/webapps/share/themes/lightTheme/images/alfresco.svg
      - ./alfresco.svg:/usr/local/tomcat/webapps/share/themes/default/images/alfresco.svg
      - ./alfresco.svg:/usr/local/tomcat/webapps/share/themes/hcBlack/images/alfresco.svg
      - ./alfresco.svg:/usr/local/tomcat/webapps/share/themes/yellowTheme/images/alfresco.svg
      - ./alfresco.svg:/usr/local/tomcat/webapps/share/themes/greyTheme/images/alfresco.svg
      - ./alfresco.svg:/usr/local/tomcat/webapps/share/themes/greenTheme/images/alfresco.svg
      - ./alfresco.svg:/usr/local/tomcat/webapps/share/themes/gdocs/images/alfresco.svg
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/lightTheme/images/app-logo-48.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/lightTheme/images/app-logo.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/default/images/app-logo-48.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/default/images/app-logo.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/yellowTheme/images/app-logo-48.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/yellowTheme/images/app-logo.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/greyTheme/images/app-logo-48.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/greyTheme/images/app-logo.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/greenTheme/images/app-logo-48.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/greenTheme/images/app-logo.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/gdocs/images/app-logo-48.png
      - ./alfresco-48.png:/usr/local/tomcat/webapps/share/themes/gdocs/images/app-logo.png
      - ./alfresco-48-white.png:/usr/local/tomcat/webapps/share/themes/hcBlack/images/app-logo-48.png
      - ./alfresco-48-white.png:/usr/local/tomcat/webapps/share/themes/hcBlack/images/app-logo.png
      - ./about-bg-msp.png:/usr/local/tomcat/webapps/share/modules/images/about-bg-vanilla.png
      - ./transparent.png:/usr/local/tomcat/webapps/share/components/images/simple+smart-medium.png
      - ./logo-msp.ico:/usr/local/tomcat/webapps/share/favicon.ico
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.share.rule=PathPrefix(`/share`)"
      - "traefik.http.routers.share.entrypoints=web,websecure"
      - "traefik.http.routers.share.tls.certresolver=letsencrypt"
      - "traefik.http.services.share.loadbalancer.server.port=8080"
    networks:
      - webproxy
    restart: unless-stopped


  solr6:
    build:
      context: ./search
      args:
        SEARCH_TAG: ${SEARCH_CE_TAG}
        SOLR_HOSTNAME: solr6
        ALFRESCO_HOSTNAME: alfresco
        ALFRESCO_COMMS: secret
        CROSS_LOCALE: "true"
        DISABLE_CONTENT_INDEXING: "false"
    mem_limit: 3744m
    environment:
      SOLR_JAVA_MEM: "-XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      SOLR_OPTS: "
        -XX:-UseLargePages
        -Dalfresco.secureComms.secret=${SOLR_SECRET:?Definir SOLR_SECRET dans .env}
      "
    depends_on:
      alfresco:
        condition: service_healthy
    volumes:
      - ./data/solr-data:/opt/alfresco-search-services/data
    networks:
      - webproxy
    restart: unless-stopped


  content-app:
    image: alfresco/alfresco-content-app:${ACA_TAG}
    mem_limit: 256m
    environment:
      APP_BASE_SHARE_URL: "${PROTOCOL}://${SERVER_NAME}:${SHARE_PORT}/#/preview/s"
      APP_CONFIG_PLUGIN_PROCESS_SERVICE: false
    depends_on:
      alfresco:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./content-app/app.config.json:/usr/share/nginx/html/app.config.json
      - ./content-app/index.html:/usr/share/nginx/html/index.html
      - ./content-app/signature-notifications.js:/usr/share/nginx/html/signature-notifications.js
      - ./alfresco.svg:/usr/share/nginx/html/assets/images/alfresco-logo-flower.svg
      - ./alfresco.svg:/usr/share/nginx/html/assets/images/alfresco-logo.svg
      - ./alfresco-white.svg:/usr/share/nginx/html/assets/images/alfresco-logo-white.svg
      - ./alfresco.svg:/usr/share/nginx/html/assets/images/app-logo.svg
      - ./logo.png:/usr/share/nginx/html/assets/images/logo.png
      - ./logo-msp.ico:/usr/share/nginx/html/assets/favicon-96x96.png
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.content-app.rule=PathPrefix(`/`)"
      - "traefik.http.routers.content-app.entrypoints=web,websecure"
      - "traefik.http.routers.content-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.content-app.loadbalancer.server.port=8080"
    networks:
      - webproxy

  traefik:
    image: traefik:v2.11
    container_name: traefik
    mem_limit: 256m
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - webproxy

networks:
  webproxy:
    driver: bridge
