header=Initier des signatures
label.workflow=Signature
label.selectWorkflowDefinition=Veuillez s\u00e9lectionner un type de signature...
title.selectWorkflowDefinition=S\u00e9lectionner un type de signature pour d\u00e9marrer
message.failure=La signature n'a pas pu \u00eatre d\u00e9marr\u00e9e
button.startWorkflow=Initier des signatures
