link.cancelWorkflow=Annuler la signature
link.deleteWorkflow=Supprimer la signature
link.viewWorkflow=Afficher l'historique
message.noWorkflows=Aucune signature
label.type=Type
label.due=\u00c9ch\u00e9ance
label.started=Initi\u00e9e
label.ended=Termin\u00e9e
label.description=Description
filter.workflows.active=Signatures en cours
filter.workflows.completed=Signatures termin\u00e9es
filter.due.today=Signatures pour aujourd'hui
filter.due.tomorrow=Signatures pour demain
filter.due.next7Days=Signatures pour les 7 prochains jours
filter.due.overdue=Signatures en retard
filter.due.noDate=Signatures sans date d'\u00e9ch\u00e9ance
filter.started.last7Days=Signatures initi\u00e9es au cours des 7 derniers jours
filter.started.last14Days=Signatures initi\u00e9es au cours des 14 derniers jours
filter.started.last28Days=Signatures initi\u00e9es au cours des 28 derniers jours
filter.priority.1=Signatures de priorit\u00e9 \u00e9lev\u00e9e
filter.priority.2=Signatures de priorit\u00e9 moyenne
filter.priority.3=Signatures de priorit\u00e9 faible
filter.workflowType=Signatures : {0}
